name: Crystal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y cmake g++-9 gcc-9 
    - name: Install project dependencies
      run: shards install
    - name: Run tests
      run: crystal spec

  build:
    runs-on: ubuntu-latest
    needs: test

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y cmake g++-9 gcc-9 

    - name: Install project dependencies
      run: shards install
    - name: Run tests
      run: crystal build

  deliver:
    runs-on: ubuntu-latest
    needs: build

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false
